stages:
  - build
  - test
  - deploy

cache:
  key: ${CI_BUILD_REF_NAME}
  paths:
    - node_modules/
    - .nuxt/
    - server/
    - static/

build:
  stage: build
  tags:
    - WenSun
  script:
    - npm install
    - npm run build
    - sudo docker build -t seciii/frontend-app:${CI_PIPELINE_ID} .

test:
  stage: test
  tags:
    - WenSun
  script:
    - echo 'developing in process'

deploy:
  stage: deploy
  tags:
    - WenSun
  only:
    - master
    - develop
    - /^release\/.*$/
    - /^hotfix\/.*$/
  script:
    - sudo cd ci/ && docker-compose down && docker-compose up -d
