stages:
  - deploy

deploy:
  stage: deploy
  tags:
    - WenSun
  only:
    - master
    - develop
    - /^release\/.*$/
    - /^hotfix\/.*$/
  script:
    - sudo docker pull registry.cn-hangzhou.aliyuncs.com/seciii/frontend-app:latest
    - sudo sh ./ci/service-down.sh
    - sudo docker run --name frontend-app -d -p 3000:3000 registry.cn-hangzhou.aliyuncs.com/seciii/frontend-app:latest
