version: 2.1

# basic env
workspace: &workspace ~/wensun/oasis

# deploy script
step_save_script: &save_script
  persist_to_workspace:
    root: .
    paths:
      - dist/
      - nginx/
      - Dockerfile

# image
step_docker_login: &docker_login
  run: |
    echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin registry.cn-hangzhou.aliyuncs.com

# SSH
step_add_ssh: &add_ssh
  add_ssh_keys:
    fingerprints:
      - b9:0e:9e:1a:c7:f8:45:ce:68:d8:c4:71:9c:79:12:0d

step_deploy_over_ssh: &deploy_over_ssh
  run:
    name: Deploy Over SSH
    command: |
      ssh $SSH_USER@$SSH_HOST < ci/proxy-restart.sh

jobs:
  deploy:
    machine:
      enabled: true
    working_directory: *workspace
    steps:
      - checkout
      - *save_script
      - *docker_login
      - *add_ssh
      - *deploy_over_ssh

workflows:
  release-app:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - master
                - develop
