version: 2.1

# referred from vuejs/vue-next
# author: Evan You

# image
step_docker_login: &docker_login
  run: |
    echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin

# SSH
step_add_ssh: &add_ssh
  add_ssh_keys:
    fingerprints:
      - 76:e0:17:fa:a1:60:03:c0:06:60:c7:6b:3b:13:ec:d5

step_deploy_over_ssh: &deploy_over_ssh
  run:
    name: Deploy Over SSH
    command: |
      ssh $SSH_USER@$SSH_HOST < nginx/proxy-restart.sh

jobs:
  deploy:
    machine:
      enabled: true
    steps:
      - *docker_login
      - *add_ssh
      - *deploy_over_ssh

workflows:
  release-entry:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - master
                - develop
